### ISSUE TITLE
Warning for missing "key" prop

### ISSUE THREAD

**Issue by jgoux** [Jador/react-hyperscript-helpers#4]
Hello,
I tried your library, which is great so far to replace JSX.
I have an issue with the "key" property, as soon as I pass more than one component in the array of children, I have the warning that I need to add a "key" prop to each children.
I'm pretty sure it's not needed with JSX when you declare components without explicitly passing an array : 
```javascript
// key prop is added automatically I suppose ?
return (
  <div>
    <Component1 />
    <Component2 />
  </div>
)
```

So my question is, is it possible to add this key prop automatically ?

**Comment by Jador** [comment]
I'm glad it's of some use to you :+1: 

Let me look at what JSX does in that case and I'll get back to you.

**Comment by Jador** [comment]
So I have been investigating this off and on the past couple of days.

Unfortunately, I am drawing up blanks. I do still have a few ideas, though.

It doesn't really look like JSX is doing anything interesting here.
Below is a comparison of one of my apps before and after using react-hyperscript-helpers. The elements look identical. Notice that in both the key is null (which appears consistent with the behavior of [React.createElement](https://github.com/facebook/react/blob/master/src/isomorphic/classic/element/ReactElement.js#L117)).

![with-jsx](https://cloud.githubusercontent.com/assets/3664391/13290645/3425294a-dada-11e5-9bd7-85b81613d1db.png)
![with-rhh](https://cloud.githubusercontent.com/assets/3664391/13290646/34268664-dada-11e5-8d1e-366443088aad.png)

I'm going to dig into the renderer when I get some time.

**Comment by neurosnap** [comment]
I'm running into the same exact issue.

**Comment by Jador** [comment]
This really bothers me. I wonder if someone at Facebook might be willing to weigh in (say perhaps @spicyj?)

**Comment by spicyj** [comment]
When children are specified as varargs, we assume they live in static positions and don't need keys.

**Comment by Jador** [comment]
Aha! I've been meaning to test that but haven't had the time. Thank you so very much!

**Comment by Jador** [comment]
Changed such that it always uses varargs for children (which appears to be consistent with other hyperscripts). Of course, this does mean you'll no longer be warned if you should use keys.

**Comment by jgoux** [comment]
Good job @Jador ! :+1: 
Now it's the time of reusing your lib. :sparkles: :dancers: :sparkles:

**Comment by davidpelaez** [comment]
Would anyone mind giving a sample into how to use it properly to avoid the keys warning? We are adding the key manually, but it feel wrong. I was looking through the issues to to see if there was something related and came to this, but unfortunately I cannot figure how to do it without manual keying of elements.

**Comment by Jador** [comment]
Ensure you are using version 1.1.0

**Comment by davidpelaez** [comment]
We did upgrade, but removing the manual `keys` attribute shows the warning. Should I have these or not? Here's for example a render that without the mnaul keys would complain:
```javascript
render() : React.Element {
    let children = [];
    const groupsElements = this.buildTableGroups();
    children.push(
      div({ key: 'groups', className: styles.groups }, [groupsElements])
    );
    if (this.props.currentBill){
      children.push(
         TableDetail( { key: 'TableDetail', ...this.props.currentBill } )
      );
    }
    return section( { className: styles.board }, [ children ] );
  }
};
```

**Comment by Jador** [comment]
I have a fair idea of what might be happening and I'm about to code up something to verify (not sitting at my dev box atm unfortunately). 

Out of curiosity, are you using TypeScript or Flow?

**Comment by davidpelaez** [comment]
@jador Flow ;), Let me know when you have a moment. We tried reading your commit but couldn't figure out how to make it work. Any help is appreciated, this is our only issue with react-hyperscript-helpers, we are totally sold besides it so thank you! :)

**Comment by Jador** [comment]
No worries. Glad you guys like it and it is of some use to you.

Okay, so it is as I suspected. Your problem is right here.

> return section( { className: styles.board }, **[ children ]** );

You have an array in an array.

If you look back at [this comment](https://github.com/Jador/react-hyperscript-helpers/issues/4#issuecomment-205992971) you'll see that when `React.createElement` receives an array explicitly it expects all of the children to have keys. So what rhh does is [spread the children](https://github.com/Jador/react-hyperscript-helpers/blob/master/src/index.js#L35) onto an args array and then [apply it to React.createElement](https://github.com/Jador/react-hyperscript-helpers/blob/master/src/index.js#L38), effectively causing the children to passed as varargs.

Since you have an array in an array, `React.createElement` still is getting an explicit array and doing what it was designed to do.

Here is the code I wrote to test this for reference

```javascript
import React    from 'react';
import ReactDOM from 'react-dom';
import { div }  from 'react-hyperscript-helpers';

const componentA = () =>
  div([
    div('hello'),
    div('world')
  ]);

const arr = [];

arr.push(div('hello'));
arr.push(div('world'));

const componentB = () =>
  div([ arr ]);

// rendering componentA produces no warning
// rendering componentB does
ReactDOM.render(componentA(), document.getElementById('container'));```

Off topic, and perhaps not the best forum for this (email me if you like), I am curious how flow is working out for you. I am quite interested in it, but am currently work in a very Windows centric environment so I haven't really had the opportunity to play around with it.
