### ISSUE TITLE
Support CSS Module Composed Selectors

### ISSUE THREAD

**Issue by Jador** [Jador/react-hyperscript-helpers#5]
Personally I am a big fan of [css modules](https://github.com/css-modules/css-modules/). The composition of selectors is just lovely.

However, if you use composition you can't just drop the result into the selector param.

Example:

``` css
.alpha {
  margin: 0 auto;
}

.omega {
  composes: alpha;
  padding: 1em;
}
```

``` javascript
import React from 'react';
import { hh, div } from 'react-hyperscript-helpers';

import classes from '../styles/some.css';

export default hh(() => div(`.${classes.omega}`, '\u03A9'));
```

The `omega` class will actually be two classes (`some_hash_a some_hash_b`) and so by dropping it into the selector param only the first class is picked up. The second one will be ignored because it is not a proper selector.

Of course there are ways to work around this. One could simply use the `className` prop as you would with JSX or do a string replace.

We could bring this concern into the library.

One way would be to produce a utility to provide a proper selector.

Another option would be to treat space delimited portions of the selector param as a class.

Or we could not be concerned about it at all.

Any thoughts?

**Comment by kjr247** [comment]
First initial terrible idea:
We could create a utility that parses the string before hand or in the react-hyperscript-helpers, (I'm assuming it's a string) and append a "." to the beginnings of each class, based on the space delimitation, so that it recognizes them. This is probably going to be my least favorite idea, but it's my initial thought though. This could be brought into the library as an extra feature, and simply add something to the beginning of the class to denote that it's composed and needs to be adjusted, so that when it sees the class it just handles it behind the scenes. This would be simple, should be fast(could be faster), but would still be tightly coupled to the library.

I really don't like the idea of string manipulation as the fix. I'm not familiar with the guts of CSS-modules or react-hyperscript-helpers, but it would be nice if they just did what they are supposed to do without the dirty/extra string manip.

Since this is a simple fix only for the use case of composable CSS selectors I kinda hate to code the fix into the library(just yet), instead it would be nice to have a util that could just be deleted later on if this problem gets fixed somewhere else.

You could have this take care of your string before hand in the components when you see it, but then it would be written all over the place. 
You could code it into the library, but then a dirty refactor would be needed if you ever want to take it out.

I think just make it a util that the library can use as a single line function call, perhaps use branching logic.
```

if(string manip needed){
fix it
}
just do the thing normally after the check()
```

simple/beautiful, fast/efficient, loosely coupled, the least complications, easiest to maintain/contribute.

I'll try to have a closer look later today.

**Comment by Pajn** [comment]
>but it would be nice if they just did what they are supposed to do
They give you space separated class names as that is what they are supposed to do in most cases (as the class attribute is space separated)

One other thought is that there could be an helper function for creating the className prop (if we want nicer syntax for that)
```javascript
import React from 'react';
import { classNames, hh, div } from 'react-hyperscript-helpers';

import classes from '../styles/some.css';

export default hh(() => div(classNames(classes.omega), '\u03A9'));
```

This helper function could also make it easier to add additional classes by accepting multiple parameters
```javascript
export default hh(() => div(classNames(classes.omega, 'other-class'), '\u03A9'));
```

An conditional classes by ignoring falsey values
```javascript
export default hh(() => div(classNames(classes.omega, isOpen && 'other-class'), '\u03A9'));
```

And finally, if not using ES7 so that object spread isn't avalible it would be nice if it handled additional attributes by supplying objects
```javascript
export default hh(() => div(classNames(classes.omega, {ariaHidden: !isOpen}), '\u03A9'));
```

**Comment by kjr247** [comment]
@Jador @Pajn 

> One other thought is that there could be an helper function for creating the className prop (if we want nicer syntax for that)

I like this so far, this is kinda what I had in mind, good job fleshing it out Pajn. 

> export default hh(() => div(classNames(classes.omega, {ariaHidden: !isOpen}), '\u03A9'));

This brings up another question I have that is somewhat related. What would be the plan for inline styles? Could we also have a separate handler for those? I'm just contemplating separation of concerns at least temporarily, and future proofing for any changes that may come up.

So perhaps something like 

`export default hh(() => div(classNames(classes.omega), inlineStyles({ display: flex }) , '\u03A9'));`

**Comment by Jador** [comment]
However this is done there will need to be a utility function. It really becomes a matter of if calling it would be the responsibility of the user.

@Pajn I do somewhat like the `classNames` function you suggest but it is really drifting into the functionality of [JedWatson/classnames](https://github.com/JedWatson/classnames). I think that it would be confusing as as his function produces a space delimited string and ours would be a css selector. Maybe if we called it something different (selector, createSelector, selectify...).

What would be the real value add of having
```javascript
export default hh(() => div(classNames(classes.omega, {ariaHidden: !isOpen}), '\u03A9'));
```
vs
```javascript
export default hh(() => div(classNames(classes.omega), { 'aria-hidden': !isOpen }, '\u03A9'));
```
Less noise?

**Comment by Pajn** [comment]
@Jador 
My thinking was that it would return a props object (an object with a space delimited className prop), but when I think about it there aren't much reason to do that. If it returns a selector instead it wouldn't need the prop handling.

@kjr247
Doesn't inline styles work as usual with React (using a style prop)?
```javascript
export default hh(() => div(classNames(classes.omega), { style: { display: flex }} , '\u03A9'));
```
Might be hard creating a helper function that's cleaner than that :)

**Comment by kjr247** [comment]
@Pajn 
It sure does. XD I just finished some components using it perfectly.

**Comment by rtsao** [comment]
https://github.com/colingourlay/hyperstyles

**Comment by Jador** [comment]
@rtsao, thanks for sharing. This is pretty clean.

Throwing out a couple of APIs that come to mind.

```javascript
export default hh(() => div('.omega', '\u03A9'));

**Comment by neurosnap** [comment]
Why not something simple like this: `const selectorToClassName = param => param.replace(' .', ' ').replace('.', ' ');`

**Comment by Jador** [comment]
The issue isn't to turn a selector into just the class name(s). rhh already does that fine. The problem is that css modules does not produce simple classes (which is a good thing) that you can simply throw a '.' in front of to turn into a selector.

So the question is, should rhh take it upon itself to make it easier/cleaner to use css modules or not? It really is a first world type of problem lol

**Comment by neurosnap** [comment]
So the issue is that your `parseSelector` is trying to smartly detect all classes within a string and css modules delimits via space and not with a `.` prefix?  Why not dumb down the `parseSelector` and simply look for the first character in the string and assume that `[space]` or `[space].` are classes?

**Comment by Jador** [comment]
That is certainly a possibility and an easy thing to do. I feel it muddies the api, though. What I'm getting at is that if you allow for that then the string is no longer a selector (keep in mind the code in question also allows you to specify an id). The semantics no longer make immediate sense.

In my view I would remove the feature before allowing for strings that don't fit the standardized pattern.

**Comment by neurosnap** [comment]
Gotcha, yeah for my personal use case I don't go beyond space delimited classes or one simple id selector so having complex combinations of ids and classes inside the selector would certainly ruin my simplistic approach.
